Vagrant.configure("2") do |config|

config.ssh.insert_key = false
config.vm.provider :virtualbox do |vb|
  vb.memory = 256
  vb.cpus = 1
end

#Disabling the default /vagrant share
config.vm.synced_folder ".", "/vagrant", disabled: true
MACHINE = ["master","slave1","slave2","slave2"]
N = 3

(0..N).each do |i|
config.vm.define "server#{i}" do |node|
  node.vm.hostname = MACHINE[i]
  node.vm.box = "centos/7"
  node.vm.network :public_network, ip: "192.168.3.#{10+i}"
  node.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config  
     sed -i 's/StrictHostKeyChecking ask/StrictHostKeyChecking no/g' /etc/ssh/sshd_config	 
     systemctl restart sshd.service
SHELL
end
end
end
